### ISSUE TITLE
ENP Connect to DB when Deployed

### ISSUE THREAD

**Issue by EvanParish** [department-of-veterans-affairs/va-enp-api#159]
## User Story - Business Need

Currently the deployed ENP code cannot connect to the database hosted in RDS. This requires some changes to how we construct the database uri. It will no longer be passed in a single environment variable and will need to be constructed from a few different ones, see Additional Info below.

- [ ] Ticket is understood, and QA has been contacted (if the ticket has a QA label).

### User Story(ies)

**As a** backend engineer   
**I want** to connect to the database when the application is deployed   
**So that** the FastAPI codebase is useable when deployed  

### Additional Info and Resources
- We will need to alter the code to build the database connection string based on the appropriate secrets. These secrets are available as environment variables.
	- `DB_AUTH`
	- `DB_HOSTNAME`
	- `DB_HOSTNAME_READ`

## Acceptance Criteria

- [ ] When ENP is deployed the code can connect to our database in RDS
- [ ] Local database connection is still intact for running the app locally
- [ ] This work is added to the sprint review slide deck (key win bullet point and demo slide)

## QA Considerations

- [ ] Endpoints that rely on database connections are able to execute successfully

**Comment by EvanParish** [comment]
I made some good progress on this ticket and tested a deployment, but the health check is failing. That seems to be constantly stopping and restarting the tasks. I'll sync with Cris and Kyle in the morning to make sure my plan makes sense. I might have to lean on Corey for the health check issues though. I tried making a change, but didn't see results right away, maybe there's some delay?

I believe the health check route needs to be `/enp` now but I'm not sure if http vs https matters. Also, when checking the logs I did see the "Application startup complete" message so that's promising.

**Comment by EvanParish** [comment]
Kyle helped me get unstuck on Friday. My inquiry to AWS also yielded the same info. The port to the ENP API needed to be allowed by the security group. With that fixed I was able to deploy and connect to the ENP DB! 

I've merged main into my branch which includes the changes to connect to the notification API DB. I added the required secrets in infra, but I think I missed a step when trying to deploy it. The secret for the notification API DB URI did not show up on the ENP task. I should have this resolved soon. I'll reach out to Corey to double check my understanding of the deployment process for ENP.

**Comment by EvanParish** [comment]
ENP is alive! I'm expecting to open the PRs for review today.

**Comment by cris-oddball** [comment]
PRs approved and merged. Infra released al the way up. ENP needs to be deployed to Perf, then tested. This will happen on Weds, 25 FEB 2025.

**Comment by cris-oddball** [comment]
Code failed to deploy to Perf. @EvanParish looking into it but has an appointment. Will raise in standup if not resolved by then.

**Comment by EvanParish** [comment]
ENP is live in perf now. We had to add admin to it for now. @coreycarvalho is making a ticket to give it proper permissions, but for now it matches dev. I'll have a PR up shortly for the required hotfix.

**Comment by cris-oddball** [comment]
### QA PASSED

- [ ] POST `/enp/db/test` tests connection to ENP db

![Image](https://github.com/user-attachments/assets/e683c4e6-20df-484c-94f2-f3c857860f51)

- [ ] GET /`enp/db/test` tests connection to ENP db

![Image](https://github.com/user-attachments/assets/d8e185cf-eca4-4809-ac21-73e56fb0e5f2)

- [ ] GET `/legacy/notifications/{{notification-id}}?enp=false` tests connection to notification-api db
Validated by sending an sms through the notification-api and then looking up the reference via this route. The route returns a 200 and null, so we have to reply on logs to see that the request was made.

![Image](https://github.com/user-attachments/assets/d943f22b-7bcc-4211-8511-bf38f1b03dfd)

![Image](https://github.com/user-attachments/assets/6676d25b-2c1b-4daf-956f-b1167bd62e10)

![Image](https://github.com/user-attachments/assets/4933c010-b368-46e0-b0bd-975f739b3fd8)
